apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-display
  namespace: knapp
spec:
  selector:
    matchLabels:
      app: event-display
  template:
    metadata:
      labels:
        app: event-display
    spec:
      containers:
      - name: event-display
        image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"        
---
apiVersion: v1
kind: Service
metadata:
  name: event-display
  namespace: knapp
spec:
  selector:
    app: event-display
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080