apiVersion: v1
kind: Pod
metadata:
  name: kafka-tools
  namespace: knapp
spec:
  containers:
    - name: kafka-tools
      image: quay.io/strimzi/kafka:0.22.1-kafka-2.7.0
      command: [ "sleep", "infinity"]
      volumeMounts:
      - name: producer-config
        mountPath: /etc/config
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"      
  volumes:
    - name: producer-config
      configMap:
        name: producer-config    
  restartPolicy: Never